version: '3.8'

services:
  simplestchat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=simplestChat=debug,mediasoup=info
    restart: unless-stopped
